[package]
name = "day4"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day4_part1"
path = "src/day4_part1.rs"

[[bin]]
name = "day4_part2"
path = "src/day4_part2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
