[package]
name = "day2"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day2_part1"
path = "src/day2_part1.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
